In [26]:
import warnings
warnings.filterwarnings("ignore")

In [27]:
# k-fold cross-validation is a model validation technique
#used to assess the performance of a machine learning 
# model by splitting the dataset into multiple train-test splits

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits =load_digits()

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [30]:
# Logistic Regression
lr = LogisticRegression()  # Instantiate the LogisticRegression class
lr.fit(x_train, y_train)  # Fit the model
lr.score(x_test,y_test)

0.9555555555555556

In [31]:
#RandomForest classifier
rf=RandomForestClassifier(n_estimators = 50)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9648148148148148

In [32]:
#SVM
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [33]:
#cross-validation
from sklearn.model_selection import cross_val_score

In [34]:
#logistic regression model performance using cross-validation
cross_val_score(LogisticRegression(),digits.data,digits.target,cv =5)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [23]:
#random forest performance using cross validation
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=5)

array([0.92777778, 0.9       , 0.9637883 , 0.96100279, 0.91643454])

In [24]:
#svm performance using cross validation
cross_val_score(SVC(),digits.data,digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [42]:
#parameter tunning using k-fold cross-validation
score1= cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=5)
np.average(score1)



0.9198978644382543

In [43]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=5)
np.average(score2)

0.9332420303311668

In [48]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=200),digits.data,digits.target,cv=5)
np.average(score3)

0.9415861962240794

In [46]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=300),digits.data,digits.target,cv=5)
np.average(score4)

0.9399241720829465

In [55]:
# Calculate the overall average of the 4 scores
# Calculate the overall average of the 4 scores
overall_avg = np.mean([np.average(score1), np.average(score2), np.average(score3), np.average(score4)])
print(f"Overall Average Score: {overall_avg:.2f}")

Overall Average Score: 0.93


In [ ]:
svc